In [ ]:
#---#| default_exp wrappers.alphatims_wrapper

# MSData_Base to AlphaTims

In [ ]:
# notebook was moved from alpharaw

In [ ]:
from alpharaw import register_all_readers
from peptdeep.alphatims_wrapper import AlphaTimsWrapper

register_all_readers()

In [ ]:
#| hide
import io
from alpharaw.legacy_msdata.mgf import ms_reader_provider

In [ ]:
#| hide
mgf = io.StringIO("""
BEGIN IONS
TITLE=02445a_BA7-TUM_HLA_7_01_01-DDA-1h-R1.8.8.3.0.dta
CHARGE=3+
RTINSECONDS=3.5418930
PEPMASS=272.276336
103.92207 5457.3
104.20045 5051.4
108.70090 5891.7
113.94175 6442.6
116.92975 40506.3
116.93716 8945.5
128.37773 6427.8
131.95308 288352.6
133.93259 7344.6
138.44611 7326.1
139.00072 41556.8
140.00319 16738.8
140.99719 9493.8
145.93156 10209.3
145.94897 10497.8
147.94559 8206.3
147.96396 30552.8
148.95543 14654.7
149.96338 234207.8
150.95096 8306.0
157.01089 84638.9
158.01357 27925.7
159.00627 16084.7
163.94281 24751.1
163.95915 32203.3
165.95605 44458.0
165.97186 11530.2
166.99500 26432.2
167.97302 9216.7
181.95230 13858.8
191.95448 66152.7
192.95538 8408.9
193.07185 9092.8
193.95313 660574.9
194.95674 23452.8
194.99008 143940.9
200.00568 19510.8
200.99942 23678.7
204.30894 9406.1
209.96466 21853.6
211.96245 65351.0
218.90355 9149.6
223.91072 11300.2
238.89684 12108.8
243.93825 10150.2
243.97040 10987.7
244.94121 8744.2
246.90314 11556.3
271.93225 29430.0
271.99219 51184.4
272.19150 31960.4
272.98602 35844.1
273.94431 11031.8
284.47998 8191.3
290.00125 66212.4
290.99539 54064.7
293.89490 10005.0
407.06372 10838.2
464.36697 9715.4
698.81390 9711.7
END IONS
BEGIN IONS
TITLE=02445a_BA7-TUM_HLA_7_01_01-DDA-1h-R1.11.11.2.0.dta
CHARGE=2+
RTINSECONDS=6.6455220
PEPMASS=287.427959
103.34669 5304.0
104.66884 5639.7
113.42419 6258.3
118.84039 5837.5
119.93203 13977.3
130.69589 6876.2
133.94824 43094.3
134.30524 7671.5
135.96359 9031.3
138.99994 8329.7
146.95573 31143.9
147.96323 12176.5
150.95151 65859.3
151.95818 24384.2
157.01105 19241.5
157.34985 7532.5
161.08838 7843.9
161.94234 20119.7
162.95146 60110.4
163.95877 183305.5
164.96657 13647.5
174.95139 150331.9
175.95258 21393.4
178.94460 11433.1
179.95316 13650.5
180.96204 15353.5
190.94572 30418.9
191.95422 61914.1
192.61461 8642.1
192.94395 12331.4
192.96207 132342.5
193.96318 19303.0
209.04164 25149.6
209.96368 154185.0
209.98361 12353.5
213.86244 11541.3
224.93071 12903.0
228.92879 8773.6
241.86043 135357.5
242.86113 20805.2
242.94327 26679.4
243.95219 29569.9
244.92361 12153.5
246.90300 16650.3
252.96521 73484.3
253.96646 11527.5
286.85858 10166.4
287.94186 18763.2
303.87665 39189.3
304.88116 11976.0
321.89087 97122.5
322.88867 28020.8
370.28696 9008.2
389.82578 13277.0
407.83545 12220.4
425.84872 13236.5
482.54852 10940.2
END IONS
""")
reader = ms_reader_provider.get_reader('mgf')
reader.import_raw(mgf)
reader.spectrum_df

,spec_idx,peak_start_idx,peak_stop_idx,rt,charge,ms_level,precursor_mz,isolation_lower_mz,isolation_upper_mz,rt_sec
0,0,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
1,1,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
2,2,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
3,3,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
4,4,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
5,5,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
6,6,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
7,7,0,60,0.059032,3.0,2,272.276336,270.276336,274.276336,3.541893
8,8,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
9,9,-1,-1,0.000000,0.0,2,0.000000,0.000000,0.000000,0.000000
10,10,60,117,0.110759,2.0,2,287.427959,285.427959,289.427959,6.645522

In [ ]:
#| hide
tims_data = AlphaTimsWrapper(reader, True)
tims_data[3.0:5.0]

,raw_indices,frame_indices,scan_indices,precursor_indices,push_indices,tof_indices,rt_values,rt_values_min,mobility_values,quad_low_mz_values,quad_high_mz_values,mz_values,intensity_values,corrected_intensity_values
0,0,0,0,1,0,9220,3.541893,0.059032,0.0,270.276336,274.276336,103.9220,5457.3,5457
1,1,0,0,1,0,12004,3.541893,0.059032,0.0,270.276336,274.276336,104.2004,5051.4,5051
2,2,0,0,1,0,57009,3.541893,0.059032,0.0,270.276336,274.276336,108.7009,5891.7,5891
3,3,0,0,1,0,109417,3.541893,0.059032,0.0,270.276336,274.276336,113.9417,6442.6,6442
4,4,0,0,1,0,139297,3.541893,0.059032,0.0,270.276336,274.276336,116.9297,40506.3,40506
5,5,0,0,1,0,139371,3.541893,0.059032,0.0,270.276336,274.276336,116.9371,8945.5,8945
6,6,0,0,1,0,253777,3.541893,0.059032,0.0,270.276336,274.276336,128.3777,6427.8,6427
7,7,0,0,1,0,289530,3.541893,0.059032,0.0,270.276336,274.276336,131.9530,288352.6,288352
8,8,0,0,1,0,309325,3.541893,0.059032,0.0,270.276336,274.276336,133.9325,7344.6,7344
9,9,0,0,1,0,354461,3.541893,0.059032,0.0,270.276336,274.276336,138.4461,7326.1,7326
10,10,0,0,1,0,360007,3.541893,0.059032,0.0,270.276336,274.276336,139.0007,41556.8,41556
11,11,0,0,1,0,370031,3.541893,0.059032,0.0,270.276336,274.276336,140.0031,16738.8,16738
12,12,0,0,1,0,379971,3.541893,0.059032,0.0,270.276336,274.276336,140.9971,9493.8,9493
13,13,0,0,1,0,429315,3.541893,0.059032,0.0,270.276336,274.276336,145.9315,10209.3,10209
14,14,0,0,1,0,429489,3.541893,0.059032,0.0,270.276336,274.276336,145.9489,10497.8,10497
15,15,0,0,1,0,449455,3.541893,0.059032,0.0,270.276336,274.276336,147.9455,8206.3,8206
16,16,0,0,1,0,449639,3.541893,0.059032,0.0,270.276336,274.276336,147.9639,30552.8,30552
17,17,0,0,1,0,459554,3.541893,0.059032,0.0,270.276336,274.276336,148.9554,14654.7,14654
18,18,0,0,1,0,469633,3.541893,0.059032,0.0,270.276336,274.276336,149.9633,234207.8,234207
19,19,0,0,1,0,479509,3.541893,0.059032,0.0,270.276336,274.276336,150.9509,8306.0,8306
20,20,0,0,1,0,540108,3.541893,0.059032,0.0,270.276336,274.276336,157.0108,84638.9,84638
21,21,0,0,1,0,550135,3.541893,0.059032,0.0,270.276336,274.276336,158.0135,27925.7,27925
22,22,0,0,1,0,560062,3.541893,0.059032,0.0,270.276336,274.276336,159.0062,16084.7,16084
23,23,0,0,1,0,609428,3.541893,0.059032,0.0,270.276336,274.276336,163.9428,24751.1,24751
24,24,0,0,1,0,609591,3.541893,0.059032,0.0,270.276336,274.276336,163.9591,32203.3,32203
25,25,0,0,1,0,629560,3.541893,0.059032,0.0,270.276336,274.276336,165.9560,44458.0,44458
26,26,0,0,1,0,629718,3.541893,0.059032,0.0,270.276336,274.276336,165.9718,11530.2,11530
27,27,0,0,1,0,639950,3.541893,0.059032,0.0,270.276336,274.276336,166.9950,26432.2,26432
28,28,0,0,1,0,649730,3.541893,0.059032,0.0,270.276336,274.276336,167.9730,9216.7,9216
29,29,0,0,1,0,789523,3.541893,0.059032,0.0,270.276336,274.276336,181.9523,13858.8,13858
30,30,0,0,1,0,889544,3.541893,0.059032,0.0,270.276336,274.276336,191.9544,66152.7,66152
31,31,0,0,1,0,899553,3.541893,0.059032,0.0,270.276336,274.276336,192.9553,8408.9,8408
32,32,0,0,1,0,900718,3.541893,0.059032,0.0,270.276336,274.276336,193.0718,9092.8,9092
33,33,0,0,1,0,909531,3.541893,0.059032,0.0,270.276336,274.276336,193.9531,660574.9,660574
34,34,0,0,1,0,919567,3.541893,0.059032,0.0,270.276336,274.276336,194.9567,23452.8,23452
35,35,0,0,1,0,919900,3.541893,0.059032,0.0,270.276336,274.276336,194.9900,143940.9,143940
36,36,0,0,1,0,970056,3.541893,0.059032,0.0,270.276336,274.276336,200.0056,19510.8,19510
37,37,0,0,1,0,979994,3.541893,0.059032,0.0,270.276336,274.276336,200.9994,23678.7,23678
38,38,0,0,1,0,1013089,3.541893,0.059032,0.0,270.276336,274.276336,204.3089,9406.1,9406
39,39,0,0,1,0,1069646,3.541893,0.059032,0.0,270.276336,274.276336,209.9646,21853.6,21853
40,40,0,0,1,0,1089624,3.541893,0.059032,0.0,270.276336,274.276336,211.9624,65351.0,65351
41,41,0,0,1,0,1159035,3.541893,0.059032,0.0,270.276336,274.276336,218.9035,9149.6,9149
42,42,0,0,1,0,1209107,3.541893,0.059032,0.0,270.276336,274.276336,223.9107,11300.2,11300
43,43,0,0,1,0,1358968,3.541893,0.059032,0.0,270.276336,274.276336,238.8968,12108.8,12108
44,44,0,0,1,0,1409382,3.541893,0.059032,0.0,270.276336,274.276336,243.9382,10150.2,10150
45,45,0,0,1,0,1409704,3.541893,0.059032,0.0,270.276336,274.276336,243.9704,10987.7,10987
46,46,0,0,1,0,1419412,3.541893,0.059032,0.0,270.276336,274.276336,244.9412,8744.2,8744
47,47,0,0,1,0,1439031,3.541893,0.059032,0.0,270.276336,274.276336,246.9031,11556.3,11556
48,48,0,0,1,0,1689322,3.541893,0.059032,0.0,270.276336,274.276336,271.9322,29430.0,29430
49,49,0,0,1,0,1689921,3.541893,0.059032,0.0,270.276336,274.276336,271.9921,51184.4,51184
50,50,0,0,1,0,1691915,3.541893,0.059032,0.0,270.276336,274.276336,272.1915,31960.4,31960
51,51,0,0,1,0,1699860,3.541893,0.059032,0.0,270.276336,274.276336,272.9860,35844.1,35844
52,52,0,0,1,0,1709443,3.541893,0.059032,0.0,270.276336,274.276336,273.9443,11031.8,11031
53,53,0,0,1,0,1814799,3.541893,0.059032,0.0,270.276336,274.276336,284.4799,8191.3,8191
54,54,0,0,1,0,1870012,3.541893,0.059032,0.0,270.276336,274.276336,290.0012,66212.4,66212
55,55,0,0,1,0,1879953,3.541893,0.059032,0.0,270.276336,274.276336,290.9953,54064.7,54064
56,56,0,0,1,0,1908949,3.541893,0.059032,0.0,270.276336,274.276336,293.8949,10005.0,10005
57,57,0,0,1,0,3040637,3.541893,0.059032,0.0,270.276336,274.276336,407.0637,10838.2,10838
58,58,0,0,1,0,3613669,3.541893,0.059032,0.0,270.276336,274.276336,464.3669,9715.4,9715
59,59,0,0,1,0,5958139,3.541893,0.059032,0.0,270.276336,274.276336,698.8139,9711.7,9711