In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
from alphapeptdeep.peptdeep.match.psm_match import PepSpecMatch_DIA

WARNING:root:WARNING: Temp mmap arrays are written to /var/folders/fh/hf8t3l1x02d42ggk3b304_rh0000gn/T/temp_mmap_37vmr95k. Cleanup of this folder is OS dependant, and might need to be triggered manually! Current space: 624,114,790,400
WARNING:root:WARNING: No Bruker libraries are available for this operating system. Mobility and m/z values need to be estimated. While this estimation often returns acceptable results with errors < 0.02 Th, huge errors (e.g. offsets of 6 Th) have already been observed for some samples!

In [3]:
psm_match = PepSpecMatch_DIA()
psm_match.min_frag_mz = 0
# psm_match.raw_data.save_hdf("/Users/wenfengzeng/data/orbi_dia/hla/20200317_QE_HFX2_LC3_DIA_RA957_R01.raw.hdf")

In [4]:
from alphabase.psm_reader.dia_psm_reader import DiannReader
psm_df = DiannReader().import_file("/Users/wenfengzeng/data/orbi_dia/hla/20200317_QE_HFX2_LC3_DIA_RA957_R01.tsv")
psm_df

,raw_name,sequence,charge,rt,rt_start,rt_stop,mobility,proteins,uniprot_ids,genes,scan_num,score,fdr,spec_idx,mods,mod_sites,nAA,rt_norm,precursor_mz,ccs
0,20200317_QE_HFX2_LC3_DIA_RA957_R01,FPTSSPTL,1,77.6566,77.4414,77.8715,0,,Q15696;Q15695,,55018,0.955796,0.001595,55017,,,8,0.648554,849.435260,0.0
1,20200317_QE_HFX2_LC3_DIA_RA957_R01,ANSAFVER,1,46.3195,46.1352,46.5349,0,,P08238;Q58FF7;P07900;P07900-2,,32623,0.999207,0.000097,32622,,,8,0.386840,893.447557,0.0
2,20200317_QE_HFX2_LC3_DIA_RA957_R01,ANVAEHQR,2,23.8646,23.7079,24.0212,0,,Q12929;Q12929-2,,16746,0.959809,0.001492,16745,,,8,0.199307,462.735940,0.0
3,20200317_QE_HFX2_LC3_DIA_RA957_R01,APAAGEEG,1,19.4263,19.2696,19.5829,0,,Q9BYE7-3;Q9BYE7,,13632,0.971328,0.001219,13631,,,8,0.162240,701.310060,0.0
4,20200317_QE_HFX2_LC3_DIA_RA957_R01,HRIVSISL,2,67.9021,67.7177,68.0252,0,,Q5VY09,,48030,0.987557,0.000713,48029,,,8,0.567089,462.784902,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20137,20200317_QE_HFX2_LC3_DIA_RA957_R01,TPSKQSNNKYAASSYLSLTPEQWK,3,78.7641,78.6414,78.8562,0,,P0DOY2;P0CF74;P0DOY3,,55811,0.999190,0.000097,55810,,,24,0.657804,910.124079,0.0
20138,20200317_QE_HFX2_LC3_DIA_RA957_R01,VDDTQFVRFDSDAASPRTEPRAPW,3,88.9499,88.7348,89.1031,0,,P30490;P30685;P30491;P10319;P18463,,63093,0.993282,0.000516,63092,,,24,0.742871,921.775562,0.0
20139,20200317_QE_HFX2_LC3_DIA_RA957_R01,VDDTQFVRFDSDAASPRGEPREPW,3,86.2703,86.1779,86.4238,0,,P30504,,61179,0.996218,0.000399,61178,,,24,0.720492,926.435317,0.0
20140,20200317_QE_HFX2_LC3_DIA_RA957_R01,ASGSGAQVGGPISSGSSASSVTVTR,3,48.6067,48.4827,48.6992,0,,P02545;P02545-3;P02545-5;P02545-4,,34247,0.985711,0.000713,34246,,,25,0.405942,736.368132,0.0
20141,20200317_QE_HFX2_LC3_DIA_RA957_R01,SGGGGGGSSGGRGSGGGSSGGSIGG,2,18.2415,18.1475,18.3042,0,,P04264;CON__P04264,,12801,0.999267,0.000097,12800,,,25,0.152345,905.388955,0.0

In [5]:
ms_files = ["/Users/wenfengzeng/data/orbi_dia/hla/20200317_QE_HFX2_LC3_DIA_RA957_R01.raw.hdf"]
df,mz_df,inten_df,merr_df = psm_match.match_ms2_multi_raw(psm_df, ms_files)

100%|██████████| 1/1 [00:07<00:00,  7.98s/it]

In [6]:
df

,raw_name,sequence,charge,rt,rt_start,rt_stop,mobility,proteins,uniprot_ids,genes,...,fdr,spec_idx,mods,mod_sites,nAA,rt_norm,precursor_mz,ccs,frag_start_idx,frag_stop_idx
0,20200317_QE_HFX2_LC3_DIA_RA957_R01,FPTSSPTL,1,77.6566,77.4414,77.8715,0,,Q15696;Q15695,,...,0.001595,55017,,,8,0.648554,849.435260,0.0,0,7
1,20200317_QE_HFX2_LC3_DIA_RA957_R01,ANSAFVER,1,46.3195,46.1352,46.5349,0,,P08238;Q58FF7;P07900;P07900-2,,...,0.000097,32622,,,8,0.386840,893.447557,0.0,7,14
2,20200317_QE_HFX2_LC3_DIA_RA957_R01,ANVAEHQR,2,23.8646,23.7079,24.0212,0,,Q12929;Q12929-2,,...,0.001492,16745,,,8,0.199307,462.735940,0.0,14,21
3,20200317_QE_HFX2_LC3_DIA_RA957_R01,APAAGEEG,1,19.4263,19.2696,19.5829,0,,Q9BYE7-3;Q9BYE7,,...,0.001219,13631,,,8,0.162240,701.310060,0.0,21,28
4,20200317_QE_HFX2_LC3_DIA_RA957_R01,HRIVSISL,2,67.9021,67.7177,68.0252,0,,Q5VY09,,...,0.000713,48029,,,8,0.567089,462.784902,0.0,28,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60421,20200317_QE_HFX2_LC3_DIA_RA957_R01,TPSKQSNNKYAASSYLSLTPEQWK,3,78.7641,78.6414,78.8562,0,,P0DOY2;P0CF74;P0DOY3,,...,0.000097,55810,,,24,0.657804,910.124079,0.0,534642,534665
60422,20200317_QE_HFX2_LC3_DIA_RA957_R01,VDDTQFVRFDSDAASPRTEPRAPW,3,88.9499,88.7348,89.1031,0,,P30490;P30685;P30491;P10319;P18463,,...,0.000516,63092,,,24,0.742871,921.775562,0.0,534665,534688
60423,20200317_QE_HFX2_LC3_DIA_RA957_R01,VDDTQFVRFDSDAASPRGEPREPW,3,86.2703,86.1779,86.4238,0,,P30504,,...,0.000399,61178,,,24,0.720492,926.435317,0.0,534688,534711
60424,20200317_QE_HFX2_LC3_DIA_RA957_R01,ASGSGAQVGGPISSGSSASSVTVTR,3,48.6067,48.4827,48.6992,0,,P02545;P02545-3;P02545-5;P02545-4,,...,0.000713,34246,,,25,0.405942,736.368132,0.0,534711,534735
60425,20200317_QE_HFX2_LC3_DIA_RA957_R01,SGGGGGGSSGGRGSGGGSSGGSIGG,2,18.2415,18.1475,18.3042,0,,P04264;CON__P04264,,...,0.000097,12800,,,25,0.152345,905.388955,0.0,534735,534759

In [7]:
inten_df

,b_z1,b_z2,y_z1,y_z2,b_modloss_z1,b_modloss_z2,y_modloss_z1,y_modloss_z2
0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,190300.578125,0.0,37765.183594,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
534754,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
534755,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
534756,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
534757,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
534758,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [8]:
from peptdeep.model.ms2 import calc_ms2_similarity
metrics_list = []
frag_len = len(inten_df)//psm_match.max_spec_per_query
_df = df.iloc[:len(df)//psm_match.max_spec_per_query].copy()
for i in range(psm_match.max_spec_per_query):
    for j in range(i+1,psm_match.max_spec_per_query):
        _df,metrics_df = calc_ms2_similarity(
            _df,
            inten_df[i*frag_len:(i+1)*frag_len],
            inten_df[j*frag_len:(j+1)*frag_len],
        )
    metrics_list.append(metrics_df)
sum(metrics_list)/len(metrics_list)

                PCC           COS            SA           SPC
count  20142.000000  20142.000000  20142.000000  20142.000000
mean       0.793184      0.801761      0.662681      0.786549
std        0.259575      0.252218      0.251722      0.137454
min       -0.050093      0.000000      0.000000      0.026527
25%        0.722388      0.736639      0.530222      0.704215
50%        0.900511      0.905750      0.724400      0.805559
75%        0.972494      0.973826      0.855859      0.894600
max        1.000003      1.000002      1.000000      1.000000
>0.90      0.510807      0.522722      0.167494      0.260136
>0.75      0.726856      0.739632      0.461060      0.635836